"""Merge TVAE-augmented data with adversarial CSVs for offline adversarial training.

Combines:
  - Base training data (TVAE-augmented from prepare_adv_data.py)
  - [optional] Extra CSVs (e.g. original train_shap_66.csv) via --extra-csv
  - Adversarial example CSVs generated by generate_adv_soict.py

The merged dataset can then be used to retrain ALL models (XGB, CatBoost,
RF, LSTM, ResDNN) via the standard training scripts — making every model
robust against the attacks in the merged set.

Pipeline position:
    adv_samples/adv_training/train_at.csv      (from prepare_adv_data.py)
    adv_samples/{target}/{target}_{attack}.csv (from generate_adv_soict.py)
        ↓  merge_adv_data.py
    adv_samples/adv_training/train_at_merged.csv
        ↓  train_tree.py --model all --train-csv <merged>
           train_dl.py   --model all --train-csv <merged>

Usage:
    # Merge TVAE base + all generated adversarial CSVs (auto-discover)
    python merge_adv_data.py --targets xgb cat rf lstm resdnn --attacks zoo hsja pgd fgsm

    # Merge specific targets/attacks only
    python merge_adv_data.py --targets lstm resdnn --attacks pgd fgsm

    # Custom paths
    python merge_adv_data.py --base-csv ../../DS/train_tvae.csv \\
        --targets lstm --attacks pgd \\
        --out-csv ../../adv_samples/adv_training/train_merged.csv
"""

import os
import sys
import argparse

# ── Path bootstrap ──────────────────────────────────────────────────────────────
_HERE  = os.path.dirname(os.path.realpath(__file__))
_FOAMI = os.path.dirname(os.path.dirname(_HERE))   # foami+/
sys.path.insert(0, _FOAMI)

from utils.paths import setup_paths, ADV_DIR, AT_TRAIN_CSV, AT_MERGED_CSV
setup_paths()

from utils.logging import setup_logging, get_logger
from utils.constants import LABEL_COL

import pandas as pd

logger = get_logger(__name__)

# Import attack/target constants lazily to avoid circular imports
def _get_constants():
    from utils.constants import ALL_TARGETS, ALL_ATTACKS
    return ALL_TARGETS, ALL_ATTACKS


def _adv_csv_path(adv_dir: str, target: str, attack: str) -> str:
    return os.path.join(adv_dir, target, f"{target}_{attack}_adv.csv")


def merge(
    base_csv: str,
    targets: list,
    attacks: list,
    adv_dir: str,
    drop_duplicates: bool,
    extra_csvs: list = None,
) -> pd.DataFrame:
    """Load base CSV + optional extra CSVs + adversarial CSVs, merge, optionally dedup.

    Args:
        base_csv:       Primary base training CSV (e.g. TVAE-augmented train_at.csv).
        targets:        Model target names whose adv CSVs to include.
        attacks:        Attack names whose adv CSVs to include.
        adv_dir:        Root directory for adversarial CSVs.
        drop_duplicates: Remove duplicate feature rows after merge.
        extra_csvs:     Additional CSVs to include before adversarial data
                        (e.g. original train_shap_66.csv).
    """

    if not os.path.exists(base_csv):
        raise SystemExit(
            f"Base training CSV not found: {base_csv}\n"
            "Run prepare_adv_data.py first."
        )

    logger.info(f"[+] Loading base data: {base_csv}")
    df_base   = pd.read_csv(base_csv, low_memory=False)
    label_col = LABEL_COL
    feat_cols = [c for c in df_base.columns if c != label_col]
    logger.info(f"[+] Base shape: {df_base.shape}")

    parts = [df_base]
    loaded, skipped = 0, 0

    for extra in (extra_csvs or []):
        if not os.path.exists(extra):
            logger.warning(f"  [!] Extra CSV not found, skip: {extra}")
            continue
        df_extra = pd.read_csv(extra, low_memory=False)
        extra_fc = [c for c in df_extra.columns if c != label_col]
        if extra_fc != feat_cols:
            logger.warning(f"  [!] Extra CSV feature mismatch ({len(extra_fc)} vs {len(feat_cols)}), skip: {extra}")
            continue
        parts.append(df_extra)
        logger.info(f"  + extra: {os.path.basename(extra)}: {df_extra.shape[0]:>7,} rows")

    for target in targets:
        for attack in attacks:
            path = _adv_csv_path(adv_dir, target, attack)
            if not os.path.exists(path):
                logger.debug(f"  skip (not found): {path}")
                skipped += 1
                continue

            df_adv = pd.read_csv(path, low_memory=False)

            # Align columns to base (in case adv CSV has extra/missing cols)
            adv_cols = [c for c in df_adv.columns if c != label_col]
            if adv_cols != feat_cols:
                logger.warning(
                    f"  {target}/{attack}: feature mismatch "
                    f"({len(adv_cols)} vs {len(feat_cols)}) — skip"
                )
                skipped += 1
                continue

            parts.append(df_adv)
            logger.info(f"  + {target:8s} / {attack:8s}: {df_adv.shape[0]:>7,} rows")
            loaded += 1

    logger.info(f"[+] Loaded {loaded} adversarial CSV(s), skipped {skipped}")

    merged = pd.concat(parts, axis=0, ignore_index=True)
    logger.info(f"[+] Merged shape (before dedup): {merged.shape}")

    if drop_duplicates:
        before  = len(merged)
        dup     = merged[feat_cols].duplicated(keep='first')
        merged  = merged[~dup].reset_index(drop=True)
        removed = before - len(merged)
        if removed:
            logger.info(f"[+] Removed {removed:,} duplicate rows")

    # ── Class distribution ─────────────────────────────────────────────────
    dist = merged[label_col].value_counts().sort_index()
    logger.info(f"[+] Class distribution:\n{dist.to_string()}")
    logger.info(f"[+] Final shape: {merged.shape}")

    return merged


def main():
    ALL_TARGETS, ALL_ATTACKS = _get_constants()

    parser = argparse.ArgumentParser(
        description="Merge TVAE-augmented data with adversarial CSVs"
    )
    parser.add_argument('--targets', '-t', nargs='+',
                        choices=ALL_TARGETS, default=ALL_TARGETS,
                        help="Which model targets' adversarial CSVs to include "
                             "(default: all)")
    parser.add_argument('--attacks', '-a', nargs='+',
                        choices=ALL_ATTACKS, default=ALL_ATTACKS,
                        help="Which attacks' adversarial CSVs to include "
                             "(default: all)")
    parser.add_argument('--base-csv', default=AT_TRAIN_CSV,
                        help=f"Base training CSV (default: {AT_TRAIN_CSV})")
    parser.add_argument('--adv-dir', default=ADV_DIR,
                        help=f"Root adversarial samples directory (default: {ADV_DIR})")
    parser.add_argument('--out-csv', default=AT_MERGED_CSV,
                        help=f"Output merged CSV (default: {AT_MERGED_CSV})")
    parser.add_argument('--no-dedup', action='store_true',
                        help="Skip duplicate row removal")
    parser.add_argument('--extra-csv', nargs='+', default=None, metavar='CSV',
                        help="Additional CSV(s) to include in the merge before adversarial "
                             "data (e.g. original train_shap_66.csv)")
    parser.add_argument('--log-level', default='INFO',
                        choices=['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'])
    args = parser.parse_args()

    setup_logging(args.log_level)

    logger.info(f"[+] Base CSV  : {args.base_csv}")
    logger.info(f"[+] Adv dir   : {args.adv_dir}")
    logger.info(f"[+] Targets   : {args.targets}")
    logger.info(f"[+] Attacks   : {args.attacks}")
    if args.extra_csv:
        logger.info(f"[+] Extra CSVs: {args.extra_csv}")
    logger.info(f"[+] Output    : {args.out_csv}")

    df = merge(
        base_csv       = args.base_csv,
        targets        = args.targets,
        attacks        = args.attacks,
        adv_dir        = args.adv_dir,
        drop_duplicates= not args.no_dedup,
        extra_csvs     = args.extra_csv,
    )

    os.makedirs(os.path.dirname(args.out_csv), exist_ok=True)
    df.to_csv(args.out_csv, index=False)
    logger.info(f"[+] Saved → {args.out_csv}")

    logger.info(
        "\n[+] Next steps — retrain all models on merged data:\n"
        f"    python pipeline/0_training/train_tree.py --model all "
        f"--train-csv {args.out_csv}\n"
        f"    python pipeline/0_training/train_dl.py   --model all "
        f"--train-csv {args.out_csv}"
    )


if __name__ == '__main__':
    main()
