"""Merge TVAE-augmented data with adversarial CSVs for offline adversarial training.

Combines:
  - Base training data (TVAE-augmented from prepare_adv_data.py)
  - [optional] Extra CSVs (e.g. original train_shap_66.csv) via --extra-csv
  - Adversarial example CSVs generated by generate_adv_soict.py

The merged dataset can then be used to retrain ALL models (XGB, CatBoost,
RF, LSTM, ResDNN) via the standard training scripts — making every model
robust against the attacks in the merged set.

Pipeline position:
    adv_samples/adv_training/train_at.csv      (from prepare_adv_data.py)
    adv_samples/{target}/{target}_{attack}.csv (from generate_adv_soict.py)
        ↓  merge_adv_data.py
    adv_samples/adv_training/train_at_merged.csv
        ↓  train_tree.py --model all --train-csv <merged>
           train_dl.py   --model all --train-csv <merged>

Usage:
    # Merge TVAE base + all generated adversarial CSVs (auto-discover)
    python merge_adv_data.py --targets xgb cat rf lstm resdnn --attacks zoo hsja pgd fgsm

    # Merge specific targets/attacks only
    python merge_adv_data.py --targets lstm resdnn --attacks pgd fgsm

    # Custom paths
    python merge_adv_data.py --base-csv ../../DS/train_tvae.csv \\
        --targets lstm --attacks pgd \\
        --out-csv ../../adv_samples/adv_training/train_merged.csv
"""

import os
import sys
import argparse

# ── Path bootstrap ──────────────────────────────────────────────────────────────
_HERE  = os.path.dirname(os.path.realpath(__file__))
_FOAMI = os.path.dirname(os.path.dirname(_HERE))   # foami+/
sys.path.insert(0, _FOAMI)

from utils.paths import setup_paths, ADV_DIR, AT_DIR, AT_TRAIN_CSV, AT_MERGED_CSV, TRAIN_CSV
setup_paths()

from utils.logging   import setup_logging, get_logger
from utils.constants import ALL_TARGETS, ALL_ATTACKS, SINGLE_TARGETS
from utils.data      import merge_adv_csvs, merge_per_model

import pandas as pd

logger = get_logger(__name__)


def main():
    parser = argparse.ArgumentParser(
        description="Merge TVAE-augmented data with adversarial CSVs"
    )
    parser.add_argument('--targets', '-t', nargs='+',
                        choices=ALL_TARGETS, default=ALL_TARGETS,
                        help="Which model targets' adversarial CSVs to include "
                             "(default: all)")
    parser.add_argument('--attacks', '-a', nargs='+',
                        choices=ALL_ATTACKS, default=ALL_ATTACKS,
                        help="Which attacks' adversarial CSVs to include "
                             "(default: all)")
    parser.add_argument('--base-csv', default=None,
                        help=f"Base training CSV (default: {AT_TRAIN_CSV} for shared, "
                             f"{TRAIN_CSV} for per-model)")
    parser.add_argument('--adv-dir', default=None,
                        help=f"Root adversarial samples directory (default: {ADV_DIR} "
                             f"for shared, {AT_DIR} for per-model)")
    parser.add_argument('--out-csv', default=AT_MERGED_CSV,
                        help=f"Output merged CSV for shared mode (default: {AT_MERGED_CSV})")
    parser.add_argument('--no-dedup', action='store_true',
                        help="Skip duplicate row removal")
    parser.add_argument('--extra-csv', nargs='+', default=None, metavar='CSV',
                        help="Additional CSV(s) to include in the merge before adversarial "
                             "data (e.g. original train_shap_66.csv)")
    parser.add_argument('--per-model', action='store_true',
                        help="Per-model merge: each model gets its own merged CSV "
                             "with model-specific adv pairs (recommended)")
    parser.add_argument('--sample-threshold', type=int, default=-1,
                        help="Max adv samples per adv CSV, balanced per label "
                             "(-1 = no limit, default: -1)")
    parser.add_argument('--log-level', default='INFO',
                        choices=['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'])
    args = parser.parse_args()

    setup_logging(args.log_level)

    if args.per_model:
        base_csv = args.base_csv or TRAIN_CSV
        adv_dir  = args.adv_dir  or AT_DIR
        out_dir  = os.path.dirname(args.out_csv) if args.out_csv != AT_MERGED_CSV else AT_DIR

        logger.info(f"[+] Per-model merge mode")
        logger.info(f"[+] Base CSV         : {base_csv}")
        logger.info(f"[+] Adv dir          : {adv_dir}")
        logger.info(f"[+] Sample threshold : {args.sample_threshold}")
        logger.info(f"[+] Output dir       : {out_dir}")

        models = [t for t in args.targets if t in SINGLE_TARGETS]
        for model in models:
            out_path = os.path.join(out_dir, f"train_at_{model}.csv")
            df = merge_per_model(
                model=model,
                base_csv=base_csv,
                adv_dir=adv_dir,
                attacks=args.attacks,
                sample_threshold=args.sample_threshold,
                drop_duplicates=not args.no_dedup,
                extra_csvs=args.extra_csv,
            )
            os.makedirs(os.path.dirname(out_path), exist_ok=True)
            df.to_csv(out_path, index=False)
            logger.info(f"[+] Saved → {out_path}")

        logger.info(
            "\n[+] Next step — retrain with per-model CSVs:\n"
            f"    python pipeline/3_adv_training/retrain_at.py --model all "
            f"--per-model-dir {out_dir}"
        )
    else:
        base_csv = args.base_csv or AT_TRAIN_CSV
        adv_dir  = args.adv_dir  or ADV_DIR

        logger.info(f"[+] Shared merge mode")
        logger.info(f"[+] Base CSV  : {base_csv}")
        logger.info(f"[+] Adv dir   : {adv_dir}")
        logger.info(f"[+] Targets   : {args.targets}")
        logger.info(f"[+] Attacks   : {args.attacks}")
        if args.extra_csv:
            logger.info(f"[+] Extra CSVs: {args.extra_csv}")
        logger.info(f"[+] Output    : {args.out_csv}")

        df = merge_adv_csvs(
            base_csv       = base_csv,
            targets        = args.targets,
            attacks        = args.attacks,
            adv_dir        = adv_dir,
            drop_duplicates= not args.no_dedup,
            extra_csvs     = args.extra_csv,
        )

        os.makedirs(os.path.dirname(args.out_csv), exist_ok=True)
        df.to_csv(args.out_csv, index=False)
        logger.info(f"[+] Saved → {args.out_csv}")

        logger.info(
            "\n[+] Next steps — retrain all models on merged data:\n"
            f"    python pipeline/0_training/train_tree.py --model all "
            f"--train-csv {args.out_csv}\n"
            f"    python pipeline/0_training/train_dl.py   --model all "
            f"--train-csv {args.out_csv}"
        )


if __name__ == '__main__':
    main()
